child_config: PegasusTests/.swiftlint_tests

disabled_rules:
- inclusive_language
- switch_case_alignment
- todo
- weak_delegate
- trailing_whitespace
- opening_brace
- type_name

indentation: tabs

large_tuple:
  warning: 4
  error: 6

line_length: 
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  warning: 200
  error: 220

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
    - app

nesting:
  type_level: 3

function_parameter_count:
  warning: 10
  error: 15

cyclomatic_complexity:
  ignores_case_statements: true

file_length:
  warning: 300
  error: 1000
  ignore_comment_only_lines: true
